CDRH/orchid

lib/orchid/engine.rb

making sure assets specific to orchid are precompiled

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/cdrh-bootstrap-variables.scss
app/assets/stylesheets/orchid.scss
app/controllers/items_controller.rb
app/helpers/orchid/facet_helper.rb
app/models/facets.rb
app/views/items/_facets.html.erb
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb
app/views/layouts/body/_contents.html.erb
app/views/layouts/body/_flash.html.erb
app/views/layouts/body/_footer.html.erb
app/views/layouts/body/_header.html.erb
config/routes.rb

Split Browse into separate pages; Add flash msgs
Add Orchid-wide SCSS; Tweak nav colors
Remove "project" facet if API URL sets collection

Browse Breakdown

---

app/views/items/index.html.erb

closes https://github.com/Willa-Cather-Archive/letters-rails/issues/21

changes search result text

---

app/views/items/_summary_boxes.html.erb

closes https://github.com/CDRH/orchid/issues/10

guesses at label for summary boxes if no Facets equivalent found

---

app/controllers/items_controller.rb
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb
config/routes.rb

Note that dots are not normally allowed as route-bound parameters
and must be allowed by adding the constraint
http://edgeguides.rubyonrails.org/routing.html#dynamic-segments
Close #21

Change Browse URLs to use . separator

---

app/helpers/orchid/sort_helper.rb
app/views/items/_sort.html.erb

This will be more API back end agnostic
Merge in sync with API sorting updates
Close #22

Change sort type "score" to "relevancy"

---

Gemfile.lock
app/assets/stylesheets/application.scss
app/views/items/_search_box.html.erb
app/views/items/index.html.erb

A few minor changes noticed while working on other issues

Miscellaneous minor changes

---

app/helpers/orchid/application_helper.rb
app/views/items/browse_facet.html.erb
app/views/layouts/body/_navbar.html.erb

Add refactored active? helper; Use with main nav
Add with simpler code and warning if only a regexp passed
Reformat code in _navbar.html.erb to not wrap
Switch other "active" class instances to active?

Active? helper

---

app/assets/stylesheets/orchid.scss
app/controllers/items_controller.rb
app/helpers/orchid/sort_helper.rb
app/views/items/_sort.html.erb
app/views/items/_summary_boxes.html.erb

Close https://github.com/Willa-Cather-Archive/letters-rails/issues/67

Sorting Default & UI Updates

---

app/assets/stylesheets/orchid.scss
app/views/items/_search_res_count.html.erb
app/views/items/index.html.erb
lib/generators/setup_generator.rb

- updates orchid generator prompt to use `v1` in demo
- standardizes how pagination is being added to search UI
- right aligns pagination
- pulls search results text into own partial and alters wording
Closes https://github.com/CDRH/orchid/issues/39

Misc patches

---

app/assets/stylesheets/orchid.scss
app/controllers/items_controller.rb
app/helpers/orchid/application_helper.rb
app/helpers/orchid/sort_helper.rb
app/views/items/_sort.html.erb
app/views/items/_sort_dropdown_item.html.erb
app/views/items/browse_facet.html.erb

Would like both Jess's and Karin's input on the UX/accessibility aspect :)
Close https://github.com/Willa-Cather-Archive/letters-rails/issues/72

Browse facet sorting

---

app/controllers/items_controller.rb
app/helpers/orchid/application_helper.rb
app/helpers/orchid/date_helper.rb
app/helpers/orchid/sort_helper.rb
app/views/items/_search_res_items.html.erb
app/views/items/browse_facet.html.erb

Also changed `has_key?` found when searching to `key?`

Switch params checks to `.present?`

---

app/assets/stylesheets/orchid.scss
app/views/items/_date_limit.html.erb
app/views/items/_sort.html.erb
app/views/items/_summary_boxes.html.erb
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb

Remove an unnecessary buffer on date limit submit button
Rename bottom-buffer classes to buffer-bottom, update element class names
Add buffer-right classes
Remove bottom margin on search-filters and combine into min-height
Change bottom margin on search summary boxes to small

Clean mix of buffer-bottom and bottom-buffer

---

README.md
config/routes.rb
lib/orchid.rb
lib/orchid/engine.rb
lib/orchid/routing.rb

orchid avoid drawing named routes the app is / will be using
creates object to describe routes, iterates through to check for off limit route names

Overridable routing

---

README.md
lib/orchid/engine.rb

Add code to load main app extensions & overrides

---

app/views/layouts/head/_meta.html.erb
migration.md

updates migration documentation for 1.2.0

change to _meta for backwards compatibility

---

README.md
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb
lib/generators/templates/.gitignore
lib/orchid/version.rb
migration.md

Found more issues with locale param when testing with upgrading an existing app
Changed to major version because of backwards compatibility with overridden templates

Multi Language Fixes

---

README.md
app/views/layouts/body/_header.html.erb
app/views/layouts/head/_head.html.erb
app/views/layouts/head/_meta.html.erb
lib/generators/setup_generator.rb
lib/generators/templates/public.yml

also generates locale files based on user input during generation

moves title, subtitle, and shortname into locales

---

app/views/layouts/body/_languages.html.erb

this occurred because I forgot, apparently, that the "languages"
setting is a string and not an array

if one language, will not show up in orchid display

---

app/controllers/items_controller.rb
app/models/facets.rb

implements "collection" to match API collection delineation
params using strings, hashes uses symbols where possible
splits very long line
lists options for browse in readable hash to shorten request line

Browse small fixes

---

app/helpers/orchid/display_helper.rb
app/views/general/index.html.erb
app/views/items/_clear_facets.html.erb
app/views/items/_date_limit.html.erb
app/views/items/_facets.html.erb
app/views/items/_paginator.html.erb
app/views/items/_search_box.html.erb
app/views/items/_search_res_items.html.erb
app/views/items/_show_metadata.html.erb
app/views/items/_sort_dropdown_item.html.erb
app/views/items/_summary_boxes.html.erb
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb
app/views/layouts/body/_footer.html.erb
app/views/layouts/body/_languages.html.erb
app/views/layouts/body/_navbar.html.erb
app/views/layouts/head/_meta.html.erb

Adds rel attributes to describe links
Fixes small bug in display
Closes https://github.com/CDRH/orchid/issues/68

Nofollow links

---

app/views/items/_paginator.html.erb

Add aria-label attributes with descriptive names, page number, etc
Remove link from current page list item so just text

Make pagination more accessible

---

app/controllers/general_controller.rb
app/controllers/items_controller.rb

error pages not altered -- will simply display site short name
item show created with overridable method for easier customization
and abbreviated by default if longer than 20 characters

adds to <title> for default pages in orchid

---

config/routes.rb
docs/README.md
lib/generators/setup_generator.rb
lib/generators/templates/config.rb
lib/generators/templates/public.yml

closes https://github.com/CDRH/orchid/issues/139
fixes a bug with title / subtitle generation
adds clarifying comments to readme
sets "section" variable for all orchid routes and includes documentation
for adding to user routes

Sections and setup

---

app/controllers/items_controller.rb
app/helpers/orchid/display_helper.rb
app/views/items/_show_metadata.html.erb
migration.md

small potentially breaking change from link: true
change to arguments
closes #152 and removes the need for https://github.com/CDRH/family_letters/commit/0fb03ab330dcc3b1497461d7ac37b00c0219dacf commit

metadata for item "show" multilanguage support

---

app/assets/config/manifest.js
app/assets/config/orchid/manifest.js
lib/generators/setup_generator.rb
migration.md

- Hero: https://github.com/rails/sprockets/issues/415#issuecomment-258514974
- Modify default manifest.js to be backwards-compatibile
with Sprockets 3 defaults and avoid breaking existing apps

Make Orchid compatible with Sprockets 4

---

app/helpers/orchid/date_helper.rb
app/views/items/_date_limit.html.erb

Addresses server-side element of #158

Server-side date filter input validation

---

app/controllers/application_controller.rb
app/helpers/orchid/application_helper.rb

- Handle paths as both strings passed in
and arrays from lookup_context.prefixes

Fix render_overridable

---

app/views/items/index.html.erb

closes https://github.com/CDRH/orchid/issues/192

removes outdated / unused code

---

CHANGELOG.md
app/assets/javascripts/application.js

closes https://github.com/CDRH/orchid/issues/210

update jquery version

---

app/assets/config/orchid/manifest.js

add favicon folder to Orchid manifest file

---

app/views/items/_facets.html.erb
app/views/items/_help.html.erb
app/views/items/_hidden_fields.html.erb
app/views/items/_search_box.html.erb
app/views/items/_summary_boxes.html.erb
app/views/items/index.html.erb
app/views/items/search_preset.html.erb
app/views/layouts/body/_footer.html.erb
app/views/layouts/body/_navbar.html.erb
app/views/layouts/head/_favicon.html.erb
app/views/layouts/head/_scripts.html.erb
app/views/layouts/head/_stylesheets.html.erb

change comments from html style to erb style
