CDRH/orchid

app/views/layouts/head/_scripts.html.erb
app/views/layouts/head/_stylesheets.html.erb

Remove use of concat and use ERB output
Add "media: nil" option to stylesheet tag,
as Rails defaults to setting `media="screen"`
but browsers default to treating as `media="all"` without it
Add output of  comment if conditional assets loaded
<%= stylesheet_link_tag ... %> and <%= javascript_include_tag ...%>
are indented awkwardly in the template source
to produce well-indented markup in page source

Sync Rails conditional asset templating

---

lib/orchid.rb
lib/orchid/engine.rb

Fix error during generator execution if one adds Orchid to the Rails app's Gemfile with Github source
Close #9 
Drop unneeded additions to asset precompile list in Orchid module's `engine.rb`

Api bridge from GitHub

---

app/helpers/orchid/application_helper.rb

Always accessible via `params["action"]` and `params["controller"]`

Drop "action" and "controller" params from URLs

---

app/helpers/orchid/application_helper.rb
app/helpers/orchid/items_helper.rb
app/views/layouts/application.html.erb
lib/generators/setup_generator.rb

Add class="site_(section)" to <html> element
Application helper site_section called from application layout view
Uses the first value from:
- Manual override in @site_section instance variable
- "home" if a request for the home page
- A sub-uri or namespace name in the path
- Path name if it matches the controller or action name
- "pages" as the last default
Change generator to copy extendable helper files to main app
Remove Orchid::ApplicationHelper include from Orchid::ItemsHelper as
included app-wide by application_helper.rb copied to main app
Close #15

Add section class to <html>; Clear up helper use

---

app/helpers/orchid/facet_helper.rb
app/views/items/_facets.html.erb

separates out behavior of selected and unselected facets
for readability
closes https://github.com/CDRH/orchid/issues/44

prevents facets from being duplicated

---

config/initializers/routes.rb
config/routes.rb
lib/orchid/routing.rb

Previous approach with `require_relative`, aside from feeling very hacky
and not the Rails way, breaks when deployed via Phusion Passenger
because of its smart spawning method to save resources
and speed up extra app process creation:
https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/
Symlink `config/routes.rb` from `config/initializers/` to properly load
`ROUTES` constant before main app's routing is processed
Remove class variables as they don't work well with Passenger smart
spawning either. Instead:
- Only call draw method from `routes.rb` if `ROUTES` defined
- Directly check drawn routes to determine whether Orchid should
draw its routes when draw method called
Check whether home path drawn, as apps will always need a home path
and its location should never change, …

Clean up Orchid::Routing to work with Passenger

---

app/controllers/items_controller.rb
lib/generators/templates/public.yml

will allow different default orderings on browse
page and search results sidebar
closes https://github.com/CDRH/orchid/issues/61

facet_sort and browse_sort separated

---

app/controllers/application_controller.rb

in sites which are not multilanguage, this is necessary to prevent
locale=en or /en/ from showing up in the URL when it is not
necessary

locale parameter optional

---

app/views/items/_summary_boxes.html.erb

prevents errors when user has requested a search result
outside of the defined filters

summary box needs to use label not info["label"]

---

app/helpers/orchid/application_helper.rb
app/views/errors/_missing_partial.html.erb
app/views/layouts/body/_languages.html.erb
app/views/layouts/head/_meta.html.erb
lib/generators/templates/public.yml
lib/orchid/routing.rb

https://github.com/CDRH/family_letters/issues/28
- raised issue of being able to get to same page via 'search' and 'es/search'
- addressed issue here by using language_default has the base URL (no language added)
and languages setting no longer lists ALL supported languages, but only
those alternate languages (non-default)
- this will require minor changes to the configuration of existing apps
- this required changing how the routes are drawn because the constraint for languages cannot be blank
even when the parameter is optional
- also changed meta and language toggle code to include default language among
the other languages, since it had previously been listed there as well
https://github.com/CDRH/family_letters/issues/26
- now passing ALL parameters to language switching links instead …

reworks orchid language handling to avoid multiple paths for same content

---

app/helpers/orchid/facet_helper.rb
app/models/facets.rb
app/views/items/_facets.html.erb
app/views/items/_search_res_items.html.erb
app/views/items/browse_facet.html.erb

if particular facet field specifies `"translate": true`, then that facet's
individual results should be translated based on the locale yml file values
has not been tested with any facets that contain special characters

supports translating API facet results with locale file

---

app/helpers/orchid/facet_helper.rb

question:  since this returns `value` by default if no other conditions were met, do we want `value.present?` to return something like "Unknown Format?" or just leave it returning nil like below?
I also tagged on a small issue while checking for empty strings and such related to facets, closes https://github.com/CDRH/orchid/issues/101

nil values causing some issues

---

app/helpers/orchid/sort_helper.rb

title_sort has removed "a" "an" "the" from the front
reference to api schema:
https://github.com/CDRH/datura/blob/dev/lib/config/api_schema.yml#L25

fixes error where we sorted by title instead of title_sort field

---

app/controllers/items_controller.rb
app/views/items/show.html.erb
app/views/items/show_not_found.html.erb

Use i18n strings
Leave image tag commented in template for copying to customize for
specialized 404 pages
Close #131

Add item-specific 404 page, overrideable template

---

app/controllers/errors_controller.rb
config/routes.rb
docs/README.md
lib/orchid/routing.rb

Separate reusable routes; Refactor routing code
- Reusable routes moved to a separate array
- Error routes given path helper names
- Error actions reverted to use `render`
- Routing loops and route skipping de-duplicated
- Draw non-reusable routes after others with i18n support
- Revise comments
Simplify prefix and default params for routes
- Refactor routing code to use built-in `scope ..., as: "name"` for
prefixing path helper names rather than Red Green approach
- Remove extra code from REUSABLE_ROUTES procs
- DRY up routing code even further by consolidating i18n route draws
- Update documentation to remove Red Green approach instructions
- Rename header to "Section Templates"

Sections Improvement

---

app/helpers/orchid/display_helper.rb
app/views/items/_search_res_items.html.erb
app/views/items/_show_metadata.html.erb

moved <li> out of metadata method and into views
makes it easier to override if called somewhere besides a <ul>, etc
but this does mean checking if field is present? before using
added support for nested fields
split into multiple methods instead of a big'n
pulled metadata_label into its own method for easier overriding
also preemptively built "length" into method arguments for future work
now search item response AND item show pages use same method for building metadata

major metadata helper overhaul

---

app/controllers/general_controller.rb

already was implemented for item pages, but has become
clear after use that we will want it for the (section)
home and about pages as well

render overridable applied for general pages

---

app/helpers/orchid/display_helper.rb

regardless of whether or not something is a link,
we want to display the appropriate language value!

fixes non-linked translations of metadata

---

app/helpers/orchid/pagination_helper.rb
app/views/items/_paginator.html.erb

Cut default number of pages on each side of current page
to two (three still allowed for projects that prefer it)
Removed last page button, since this seems unrealistic to
be important in large result sets
closes https://github.com/CDRH/orchid/issues/175

Pagination alterations

---

CHANGELOG.md
app/views/items/_paginator.html.erb

I'm guessing this was introduced here:
https://github.com/CDRH/orchid/commit/4079e0067b6129789300c869c1702169280c1623
but I am impressed we didn't notice until now
as one might expect, if there are no prior pages then it should not be displaying the minimum (nonexistent) prior page

fixes pagination bug where page 2 of search errors

---

CHANGELOG.md
app/helpers/orchid/pagination_helper.rb
app/views/items/_paginator.html.erb

the issue was that if you had a 2 page search result,
the second page was not displaying because the "last" page was
not in the list of next pages, and the last page is also no longer
available by default
fixed by adding the total page number to the pages_next
and make sure to display dots if there are more results after
the current range max page

fixes bug with paginating results of exactly two pages

---

CHANGELOG.md
app/views/items/_clear_facets.html.erb
app/views/items/_date_limit.html.erb
app/views/items/_facets.html.erb
app/views/items/_search_box.html.erb
app/views/items/_summary_boxes.html.erb
app/views/items/browse.html.erb
app/views/items/browse_facet.html.erb

changes "search_path" hardcodes to route_path to allow overrides
tested insofar as an override works for the search_box, and all browse pages / etc
appear to be working normally with default search_path behavior

Route path

---

app/views/items/_date_limit.html.erb
app/views/items/_facets.html.erb

this came up when we were working on the African Poetry Digital Portal and found that some sections required a date search while others did not, and found it difficult to select specific filters using CSS.

attaches classes to filter selection for easier styling

---

CHANGELOG.md
app/helpers/orchid/application_helper.rb
app/views/layouts/body/_languages.html.erb
app/views/layouts/head/_language.html.erb
lib/generators/setup_generator.rb
lib/generators/templates/public.yml
lib/orchid/routing.rb

OK there are two issues here:
1.  `languages` appeared in multiple places in the public.yml file, but only the first was intended to be configured based on user language preferences during setup.  To mitigate that, this has now been named `all_languages`
2.  The resulting YAML was still invalid because of recent updates to the psyche gem. Now the thumbnail size is surrounded in quotation marks to make this valid

fix language config problem

---

CHANGELOG.md
app/controllers/items_controller.rb
app/services/api_bridge/query.rb
app/services/api_bridge/response.rb
app/views/items/_search_res_count.html.erb
app/views/items/_search_res_items.html.erb
app/views/items/_sort_and_page_ui.html.erb
app/views/items/browse_facet.html.erb
config/locales/en.yml
config/locales/es.yml

possibly addresses https://github.com/CDRH/orchid/issues/198
If the API sends an error response (like for example, if it is down entirely), this will create a friendlier message to the user than the entire page crashing and burning.  We may want to consider, possibly as future issues because I really think this is in general a big improvement, trying to pass through different messages depending on whether there was just a bad query vs that the API is down entirely.

catches api error and adds flash warning to affected pages

---

app/controllers/items_controller.rb

This reverts commit e6be8829116bf9436f7a0ad101dc6da3b858ed9d.
Reverts #229 and fixes #232, since the original error-checking code works under most circumstances.

Fix handling of check_response 
